# SPDX-FileCopyrightText: Copyright (c) 2026 The Newton Developers
# SPDX-License-Identifier: Apache-2.0

###########################################################################
# Example Craig-Bampton Multi-Interface T-Bracket
#
# Loads a three-interface Craig-Bampton ROM generated by MATLAB/Octave and
# rotates its top interface about local +Z between -180 and +180 degrees.
# The finite angle belongs to the rigid frame; the small elastic response is
# compared at every substep with an independently integrated Octave base-
# excitation reference.
#
# Command:
#   uv run --extra examples python \
#       newton/examples/fea/cb_multi_interface/example_cb_multi_interface.py \
#       --viewer gl
#
###########################################################################

from pathlib import Path

import numpy as np
import warp as wp

import newton
import newton.examples
from newton.examples.basic._reduced_elastic import find_free_joint_q_start, quat_rotate, set_camera_from_bounds
from newton.examples.basic._reduced_elastic_contact import apply_kinematic_targets

EXAMPLE_DIR = Path(__file__).resolve().parent


def _load_csv(name: str, *, dtype: type = float) -> np.ndarray:
    """Load a numeric CSV matrix exported by the Octave reference."""
    return np.loadtxt(EXAMPLE_DIR / name, delimiter=",", dtype=dtype, ndmin=2)


def _quat_conjugate(quaternion: np.ndarray) -> np.ndarray:
    result = np.array(quaternion, dtype=np.float64, copy=True)
    result[:3] *= -1.0
    return result


def _quat_multiply(left: np.ndarray, right: np.ndarray) -> np.ndarray:
    left_xyz = left[:3]
    right_xyz = right[:3]
    return np.array(
        [
            *(left[3] * right_xyz + right[3] * left_xyz + np.cross(left_xyz, right_xyz)),
            left[3] * right[3] - np.dot(left_xyz, right_xyz),
        ],
        dtype=np.float64,
    )


def _quat_to_rotation_vector(quaternion: np.ndarray) -> np.ndarray:
    quaternion = np.asarray(quaternion, dtype=np.float64)
    quaternion = quaternion / max(float(np.linalg.norm(quaternion)), 1.0e-12)
    if quaternion[3] < 0.0:
        quaternion = -quaternion
    vector_norm = float(np.linalg.norm(quaternion[:3]))
    if vector_norm < 1.0e-10:
        return 2.0 * quaternion[:3]
    angle = 2.0 * np.arctan2(vector_norm, float(quaternion[3]))
    return angle * quaternion[:3] / vector_norm


class Example:
    def __init__(self, viewer, args):
        metadata = _load_csv("rotation_reference_metadata.csv").ravel()
        self.sim_dt = float(metadata[0])
        self.reference_step_count = int(metadata[1])
        self.rotation_period = float(metadata[2])
        self.rotation_amplitude = float(metadata[3])
        self.top_interface_index = int(metadata[4]) - 1
        self.rotation_joint_stiffness = float(metadata[5])
        self.fixed_interface_mode_count = 6
        self.fps = 60
        self.frame_dt = 1.0 / self.fps
        self.sim_substeps = max(1, int(round(self.frame_dt / self.sim_dt)))
        if not np.isclose(self.sim_substeps * self.sim_dt, self.frame_dt):
            raise ValueError("The Octave reference time step must divide one rendered frame")
        self.sim_time = 0.0
        self.render_time = 0.0
        self.step_count = 0

        self.viewer = viewer
        self.args = args

        points = _load_csv("cb_rom_points.csv").astype(np.float32)
        faces = _load_csv("cb_rom_faces.csv", dtype=int).astype(np.int32) - 1
        interfaces = _load_csv("cb_rom_interfaces.csv")
        mass = _load_csv("cb_rom_mass.csv")
        stiffness = _load_csv("cb_rom_stiffness.csv")
        damping = _load_csv("cb_rom_damping.csv")
        self.recovery = _load_csv("cb_rom_recovery.csv")
        self.reference_probe_points = _load_csv("reference_probe_points.csv")
        self.reference_state = _load_csv("rotation_reference_reduced_state.csv")
        self.reference_probes = _load_csv("rotation_reference_probe_displacement.csv")
        self.reference_frequencies = _load_csv("rotation_reference_frequencies_hz.csv").ravel()

        self.generator = newton.ModalGeneratorCraigBampton(
            interface_positions=interfaces,
            mass_matrix=mass,
            stiffness_matrix=stiffness,
            damping_matrix=damping,
            sample_points=points,
            recovery_matrix=self.recovery,
            interface_names=("left", "right", "top"),
            label="octave_three_interface_t_bracket",
        )
        self.basis = self.generator.build()
        self.top_interface_position = interfaces[self.top_interface_index].astype(np.float64)

        self.probe_sample_indices = np.array(
            [
                int(np.argmin(np.linalg.norm(points.astype(np.float64) - probe, axis=1)))
                for probe in self.reference_probe_points
            ],
            dtype=np.int32,
        )
        probe_distances = np.linalg.norm(
            points[self.probe_sample_indices].astype(np.float64) - self.reference_probe_points,
            axis=1,
        )
        if float(np.max(probe_distances)) > 1.0e-7:
            raise ValueError("Reference probe points do not match ROM samples")
        self.probe_recovery_rows = np.concatenate(
            [np.arange(3 * sample, 3 * sample + 3) for sample in self.probe_sample_indices]
        )

        builder = newton.ModelBuilder(gravity=0.0)
        shape_cfg = newton.ModelBuilder.ShapeConfig()
        shape_cfg.density = 0.0
        shape_cfg.has_shape_collision = False
        shape_cfg.has_particle_collision = False

        self.frame_position = np.array([0.0, 0.0, 0.8], dtype=np.float64)
        initial_transform = wp.transform(wp.vec3(*self.frame_position), wp.quat_identity())
        self.base = builder.add_body(
            xform=initial_transform,
            mass=1.0,
            inertia=wp.mat33(1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0),
            is_kinematic=True,
            label="top_axis_drive",
        )
        builder.add_shape_cylinder(
            self.base,
            xform=wp.transform(wp.vec3(*self.top_interface_position), wp.quat_identity()),
            radius=0.045,
            half_height=0.12,
            cfg=shape_cfg,
            label="top_interface_axis",
        )

        self.body = builder.add_body_elastic(
            xform=initial_transform,
            com=wp.vec3(*self.generator.com.astype(np.float32)),
            inertia=wp.mat33(*self.generator.inertia.astype(np.float32).ravel()),
            mass=self.generator.mass,
            mode_q=np.zeros(self.basis.mode_count, dtype=np.float32),
            modal_basis=self.basis,
            lock_inertia=True,
            label="craig_bampton_three_port_t_bracket",
        )
        builder.add_shape_mesh(
            self.body,
            mesh=newton.Mesh(points, faces.ravel(), compute_inertia=False),
            cfg=shape_cfg,
            label="three_port_t_bracket_surface",
        )
        top_transform = wp.transform(wp.vec3(*self.top_interface_position), wp.quat_identity())
        builder.add_joint_fixed(
            parent=self.base,
            child=self.body,
            parent_xform=top_transform,
            child_xform=top_transform,
            label="top_interface_rotation_drive",
        )
        builder.color()

        self.model = builder.finalize()
        self.model.elastic_render_point_total_count = 0
        self.state_0 = self.model.state()
        self.state_1 = self.model.state()
        self.control = self.model.control()
        self.contacts = None

        elastic_joint = int(self.model.elastic_joint.numpy()[0])
        elastic_q_start = int(self.model.joint_q_start.numpy()[elastic_joint])
        elastic_qd_start = int(self.model.joint_qd_start.numpy()[elastic_joint])
        self.modal_q_slice = slice(elastic_q_start + 7, elastic_q_start + 7 + self.basis.mode_count)
        base_q_start, base_qd_start = find_free_joint_q_start(self.model, self.base)
        self._base_q_starts = {self.base: base_q_start}
        self._base_qd_starts = {self.base: base_qd_start}

        self.solver = newton.solvers.SolverVBD(
            self.model,
            iterations=16,
            rigid_joint_linear_ke=self.rotation_joint_stiffness,
            rigid_joint_angular_ke=self.rotation_joint_stiffness,
            rigid_joint_linear_kd=0.0,
            rigid_joint_angular_kd=0.0,
            rigid_joint_adaptive_stiffness=False,
        )

        initial_targets = self._base_targets(0.0)
        initial_velocities = self._base_velocities(0.0)
        apply_kinematic_targets(
            self.state_0,
            self._base_q_starts,
            initial_targets,
            initial_velocities,
            self._base_qd_starts,
        )
        apply_kinematic_targets(
            self.state_1,
            self._base_q_starts,
            initial_targets,
            initial_velocities,
            self._base_qd_starts,
        )
        for state in (self.state_0, self.state_1):
            joint_qd = state.joint_qd.numpy()
            body_qd = state.body_qd.numpy()
            angular_speed = self._rotation_kinematics(0.0)[1]
            joint_qd[elastic_qd_start + 3 : elastic_qd_start + 6] = [0.0, 0.0, angular_speed]
            body_qd[self.body] = [0.0, 0.0, 0.0, 0.0, 0.0, angular_speed]
            state.joint_qd.assign(joint_qd)
            state.body_qd.assign(body_qd)

        self.max_reduced_coordinate_error = 0.0
        self.max_probe_displacement_error = 0.0
        self.max_reference_reduced_coordinate = 0.0
        self.max_reference_probe_displacement = 0.0
        self.max_top_interface_error = 0.0
        self.min_rotation_angle = 0.0
        self.max_rotation_angle = 0.0
        self.current_rotation_angle = 0.0

        self.viewer.set_model(self.model)
        self.viewer.show_elastic_strain = True
        self.viewer.elastic_strain_color_max = 2.0e-3
        bounds_min = np.array([-0.85, -0.85, self.frame_position[2] - 0.2])
        bounds_max = np.array([0.85, 0.85, self.frame_position[2] + 0.75])
        set_camera_from_bounds(self.viewer, bounds_min, bounds_max, np.array([-0.8, -1.0, 0.55]))

        self._compare_reference(0)

    def _rotation_kinematics(self, time: float) -> tuple[float, float, float]:
        frequency = 2.0 * np.pi / self.rotation_period
        angle = self.rotation_amplitude * np.sin(frequency * time)
        angular_speed = self.rotation_amplitude * frequency * np.cos(frequency * time)
        angular_acceleration = -self.rotation_amplitude * frequency * frequency * np.sin(frequency * time)
        return float(angle), float(angular_speed), float(angular_acceleration)

    def _base_targets(self, time: float) -> dict[int, tuple[wp.vec3, wp.quat]]:
        angle = self._rotation_kinematics(time)[0]
        orientation = wp.quat_from_axis_angle(wp.vec3(0.0, 0.0, 1.0), angle)
        return {self.base: (wp.vec3(*self.frame_position), orientation)}

    def _base_velocities(self, time: float) -> dict[int, tuple[wp.vec3, wp.vec3]]:
        angular_speed = self._rotation_kinematics(time)[1]
        return {self.base: (wp.vec3(0.0, 0.0, 0.0), wp.vec3(0.0, 0.0, angular_speed))}

    def _relative_reduced_coordinates(self) -> np.ndarray:
        body_q = self.state_0.body_q.numpy()
        base_pose = body_q[self.base].astype(np.float64)
        elastic_pose = body_q[self.body].astype(np.float64)
        base_inverse = _quat_conjugate(base_pose[3:7])
        relative_translation = quat_rotate(base_inverse, elastic_pose[:3] - base_pose[:3])
        relative_orientation = _quat_multiply(base_inverse, elastic_pose[3:7])
        relative_rotation = _quat_to_rotation_vector(relative_orientation)
        rigid_coordinates = np.concatenate((relative_translation, relative_rotation))

        modal_q = self.state_0.joint_q.numpy()[self.modal_q_slice].astype(np.float64)
        return self.generator.rigid_matrix @ rigid_coordinates + self.generator.modal_matrix @ modal_q

    def _compare_reference(self, row: int) -> None:
        reduced_q = self._relative_reduced_coordinates()
        reduced_dof_count = self.generator.reduced_dof_count
        expected_q = self.reference_state[row, 4 : 4 + reduced_dof_count]
        reduced_error = float(np.max(np.abs(reduced_q - expected_q)))
        self.max_reduced_coordinate_error = max(self.max_reduced_coordinate_error, reduced_error)
        self.max_reference_reduced_coordinate = max(
            self.max_reference_reduced_coordinate,
            float(np.max(np.abs(expected_q))),
        )

        probe_displacement = (self.recovery[self.probe_recovery_rows] @ reduced_q).reshape((-1, 3))
        expected_probe_displacement = self.reference_probes[row, 4:].reshape((-1, 3))
        probe_error = float(np.max(np.abs(probe_displacement - expected_probe_displacement)))
        self.max_probe_displacement_error = max(self.max_probe_displacement_error, probe_error)
        self.max_reference_probe_displacement = max(
            self.max_reference_probe_displacement,
            float(np.max(np.linalg.norm(expected_probe_displacement, axis=1))),
        )

        top_start = 6 * self.top_interface_index
        self.max_top_interface_error = max(
            self.max_top_interface_error,
            float(np.linalg.norm(reduced_q[top_start : top_start + 6])),
        )
        angle = float(self.reference_state[row, 1])
        self.current_rotation_angle = angle
        self.min_rotation_angle = min(self.min_rotation_angle, angle)
        self.max_rotation_angle = max(self.max_rotation_angle, angle)

    def step(self):
        for _ in range(self.sim_substeps):
            next_row = self.step_count + 1
            next_time = next_row * self.sim_dt
            targets = self._base_targets(next_time)
            velocities = self._base_velocities(next_time)
            apply_kinematic_targets(
                self.state_0,
                self._base_q_starts,
                targets,
                velocities,
                self._base_qd_starts,
            )
            self.state_0.clear_forces()
            self.solver.step(self.state_0, self.state_1, self.control, self.contacts, self.sim_dt)
            self.state_0, self.state_1 = self.state_1, self.state_0
            apply_kinematic_targets(
                self.state_0,
                self._base_q_starts,
                targets,
                velocities,
                self._base_qd_starts,
            )
            self.sim_time = next_time
            self.step_count = next_row
            if next_row <= self.reference_step_count:
                self._compare_reference(next_row)
        self.render_time += self.frame_dt

    def render(self):
        self.viewer.begin_frame(self.render_time)
        self.viewer.log_state(self.state_0)
        self.viewer.end_frame()

    def gui(self, ui):
        reduced_relative_error = self.max_reduced_coordinate_error / max(
            self.max_reference_reduced_coordinate,
            1.0e-12,
        )
        probe_relative_error = self.max_probe_displacement_error / max(
            self.max_reference_probe_displacement,
            1.0e-12,
        )
        ui.text(f"Top-axis rotation: {np.rad2deg(self.current_rotation_angle):+.1f} deg")
        ui.separator()
        ui.text("Newton / Octave comparison")
        ui.text(f"Reduced-coordinate max error: {100.0 * reduced_relative_error:.2f}%")
        ui.text(f"Recovered-probe max error: {100.0 * probe_relative_error:.2f}%")
        ui.text(f"Top-interface slip: {self.max_top_interface_error:.3e}")

    def test_final(self):
        if self.generator.interface_count != 3:
            raise AssertionError(f"expected three interfaces, got {self.generator.interface_count}")
        if self.generator.fixed_interface_mode_count != self.fixed_interface_mode_count:
            raise AssertionError(
                f"expected {self.fixed_interface_mode_count} fixed-interface modes, "
                f"got {self.generator.fixed_interface_mode_count}"
            )
        expected_mode_count = 6 * self.generator.interface_count + self.fixed_interface_mode_count - 6
        if self.basis.mode_count != expected_mode_count:
            raise AssertionError(f"expected {expected_mode_count} elastic modes, got {self.basis.mode_count}")
        if self.step_count < self.reference_step_count:
            raise AssertionError(f"reference comparison needs {self.reference_step_count} steps, got {self.step_count}")
        angle_tolerance = np.deg2rad(0.5)
        if self.min_rotation_angle > -self.rotation_amplitude + angle_tolerance:
            raise AssertionError(f"top axis reached only {np.rad2deg(self.min_rotation_angle)} degrees")
        if self.max_rotation_angle < self.rotation_amplitude - angle_tolerance:
            raise AssertionError(f"top axis reached only {np.rad2deg(self.max_rotation_angle)} degrees")
        if self.reference_frequencies.shape[0] != self.generator.reduced_dof_count:
            raise AssertionError(
                f"expected {self.generator.reduced_dof_count} top-supported frequencies, "
                f"got {self.reference_frequencies.shape[0]}"
            )
        if self.max_reference_probe_displacement < 1.0e-5:
            raise AssertionError("top-axis acceleration did not excite measurable deformation")
        if self.max_top_interface_error > 5.0e-4:
            raise AssertionError(f"top Craig-Bampton interface slipped by {self.max_top_interface_error}")
        reduced_relative_error = self.max_reduced_coordinate_error / self.max_reference_reduced_coordinate
        probe_relative_error = self.max_probe_displacement_error / self.max_reference_probe_displacement
        if reduced_relative_error > 0.03:
            raise AssertionError(
                f"Newton reduced-coordinate error is {100.0 * reduced_relative_error:.3g}% of the Octave response"
            )
        if probe_relative_error > 0.03:
            raise AssertionError(
                f"Newton recovered-probe error is {100.0 * probe_relative_error:.3g}% of the Octave response"
            )
        if self.max_reduced_coordinate_error > 5.0e-4:
            raise AssertionError(
                f"Newton reduced coordinates diverged from the Octave reference: {self.max_reduced_coordinate_error}"
            )
        if self.max_probe_displacement_error > 2.0e-4:
            raise AssertionError(
                f"Newton recovered displacement diverged from the Octave reference: "
                f"{self.max_probe_displacement_error} m"
            )
        if not np.isfinite(self.state_0.joint_q.numpy()).all():
            raise AssertionError("joint coordinates contain non-finite values")


if __name__ == "__main__":
    parser = newton.examples.create_parser()
    parser.set_defaults(num_frames=240)
    viewer, args = newton.examples.init(parser)
    example = Example(viewer, args)
    newton.examples.run(example, args)
